# Generated by Django 5.2 on 2025-05-01 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(to='training.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='accounts.subject'),
        ),
    ]
