# Generated by Django 5.2 on 2025-05-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_period_and_more'),
    ]

    operations = [
    ]
