# Generated by Django 5.2 on 2025-05-01 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=4)),
                ('trained_model', models.FileField(blank=True, null=True, upload_to='models/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.department')),
                ('subjects', models.ManyToManyField(to='accounts.subject')),
            ],
            options={
                'unique_together': {('department', 'batch')},
            },
        ),
    ]
