# Generated by Django 5.2 on 2025-05-03 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='trained_model',
        ),
        migrations.AlterField(
            model_name='class',
            name='batch',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Batch must be a 4-digit year (e.g., 2023).')]),
        ),
    ]
